image: lorisleiva/laravel-docker:8.2

stages:
  - build
  - deploy

build_test:
  stage: build
  script:
    - composer install --no-interaction --prefer-dist
    - cp .env.example .env
    - php artisan key:generate
    - php artisan config:cache
  cache:
    paths:
      - vendor/

deploy_krystal_test:
  stage: deploy
  needs:
    - build_test
  cache:
    paths:
      - vendor/
  variables:
    SSH_PRIVATE_KEY: "SSH_PRIVATE_KEY_NOT_PROVIDED"
    UNIX_USERNAME: "default"
    SERVER_DOMAIN: "ssh.readererer.com"
    SERVER_PORT: "22"
    TEST_DOMAIN: "readererer.com"
  script:
    - composer global require --prefer-dist laravel/envoy=~2.9.0 --no-interaction --prefer-dist --quiet
    # Add the private SSH key to the build environment
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/gitlab
    - chmod 600 ~/.ssh/gitlab
    - ssh-add ~/.ssh/gitlab
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    # Temporary SSH test
    - ssh -T $UNIX_USERNAME@$SERVER_DOMAIN -p $SERVER_PORT
    - ssh -T git@gitlab.com
    # Run Envoy
    - envoy run deploy --branch=develop --domain=$TEST_DOMAIN --unix_username=$UNIX_USERNAME --server_domain=$SERVER_DOMAIN --server_port=$SERVER_PORT --seed_database=1
  only:
    - develop

deploy_krystal_demo:
  stage: deploy
  needs:
    - build_test
  cache:
    paths:
      - vendor/
  variables:
    SSH_PRIVATE_KEY: "SSH_PRIVATE_KEY_NOT_PROVIDED"
    UNIX_USERNAME: "default"
    SERVER_DOMAIN: "ssh.readererer.com"
    SERVER_PORT: "22"
    DEMO_DOMAIN: "readererer.com"
  script:
    - composer global require --prefer-dist laravel/envoy=~2.9.0 --no-interaction --prefer-dist --quiet
    # Add the private SSH key to the build environment
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/gitlab
    - chmod 600 ~/.ssh/gitlab
    - ssh-add ~/.ssh/gitlab
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    # Temporary SSH test
    - ssh -T $UNIX_USERNAME@$SERVER_DOMAIN -p $SERVER_PORT
    - ssh -T git@gitlab.com
    # Run Envoy
    - envoy run deploy --branch=main --domain=$DEMO_DOMAIN --unix_username=$UNIX_USERNAME --server_domain=$SERVER_DOMAIN --server_port=$SERVER_PORT --seed_database=0
  only:
    - /^v.*$/
  except:
    - branches
