image: lorisleiva/laravel-docker:8.2

stages:
  - build
  - deploy

composer:
  stage: build
  script:
    - composer install --no-interaction --prefer-dist
    - cp .env.example .env
    - php artisan key:generate
    - php artisan config:cache
  cache:
    paths:
      - vendor/
  only:
    - tags
  except:
    - branches

deploy_krystal:
  stage: deploy
  dependencies:
    - composer
  cache:
    paths:
      - vendor/
  script:
    - composer global require --prefer-dist laravel/envoy=~2.9.0 --no-interaction --prefer-dist --quiet
    # Add the private SSH key to the build environment
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/gitlab
    - chmod 600 ~/.ssh/gitlab
    - ssh-add ~/.ssh/gitlab
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    # Temporary SSH test
    - ssh -T $UNIX_USERNAME@$SERVER_DOMAIN -p $SERVER_PORT
    - ssh -T git@gitlab.com
    # Run Envoy
    - envoy run deploy --branch=main --domain=$DOMAIN --unix_username=$UNIX_USERNAME
  only:
    - tags
  except:
    - branches
