import './bootstrap';
import './toggle-password-visibility';
import "@tabler/core/dist/js/tabler.min.js";
import "@tabler/core/dist/js/demo-theme.min.js";
import "apexcharts/dist/apexcharts.min.js";
import "autosize/dist/autosize.min.js";
import "choices.js/public/assets/scripts/choices.min.js";
import "countup.js/dist/countUp.min.js";
import "flatpickr/dist/flatpickr.min.js";
import "imask/dist/imask.min.js";
import "jsvectormap/dist/jsvectormap.min.js"
import "litepicker/dist/js/main.js";
import "nouislider/dist/nouislider.min.js";
import "tom-select/dist/js/tom-select.complete.min.js";
